[[redirects]]
  from = "https://aea8-93-84-179-145.eu.ngrok.io"
  to = "https://statuesque-lamington-6e57a1.netlify.app"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"